const swaggerAutogen = require('swagger-autogen')()

const outputFile = './src/test/swagger_output.json'
const endpointsFiles = ['./src/routes/products-routes.js']


const doc = {
    info: {
        version: "1.0.0",
        title: "AP NodeJs",
        description: "Documentation automatically generated by the <b>swagger.autogen</b> module."
    },
    host: "api-products-nodejs.herokuapp.com",
    basePath: "/",
    schemes: ['https'],
    consumes: ['application/json'],
    produces: ['application/json']
}

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./app')
})